# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/

TARGET = btc.out
SRCS = main.cpp BitcoinExchange.cpp

include ../template.mk

main.cpp BitcoinExchange.cpp: BitcoinExchange.hpp
