# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/

TARGET = test_positive_merge_me.out
SRCS = main.cpp PmergeMe.cpp

include ../template.mk

main.cpp PmergeMe.cpp: PmergeMe.hpp
